# --- Hypridle Configuration for Nirakase ---

general {
    # Command to lock the screen. (Prevents launching it twice).
    lock_cmd = pidof swaylock || swaylock
    
    # Before the laptop suspends (e.g. closing the lid), lock the session.
    before_sleep_cmd = loginctl lock-session
    
    # Upon waking from suspend, Niri turns on the monitors natively.
    after_sleep_cmd = niri msg action power-on-monitors
}

# 1. Dim the screen after 2.5 minutes (Optional, requires brightnessctl)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Lock the session after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 3. Turn off the monitor after 5.5 minutes to save power
listener {
    timeout = 330
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# 4. Suspend system
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
