[main]
# include=~/.config/nirakase/current/theme/foot.ini
include=~/.config/foot/theme/catppuccin-mocha.ini
term=xterm-256color
font=JetBrainsMono Nerd Font:size=9
pad=14x14
initial-window-mode=windowed
workers=0

[scrollback]
lines=10000

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[key-bindings]
# clipboard-copy=Control+Insert
# primary-paste=none
# clipboard-paste=Shift+Insert

# History navigation (Scroll)
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
scrollback-up-line=Shift+Up
scrollback-down-line=Shift+Down

# Search text in the terminal history
search-start=Control+f

# URLs: Activate mode to open links
show-urls-launch=Control+k

# Clone terminal: Open another Foot window in the exact same directory
spawn-terminal=Control+Shift+n

[search-bindings]
# Search mode shortcuts (Control+f)
cancel=Control+g Control+c Escape
commit=Return
find-prev=Alt+n
find-next=Control+n

[csd]
size=0


